//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Friendshipets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedidos
    {
        public int IDPedido { get; set; }
        public int IDCliente { get; set; }
        public int IDCarrito { get; set; }
        public Nullable<int> IDFactura { get; set; }
        public System.DateTime FechaPedido { get; set; }
        public string EstadoPedido { get; set; }
        public decimal MontoTotal { get; set; }
        public string DireccionEnvio { get; set; }
    
        public virtual CarritoCompras CarritoCompras { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual Facturacion Facturacion { get; set; }
    }
}
