//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Friendshipets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productos()
        {
            this.DetalleCarrito = new HashSet<DetalleCarrito>();
            this.DetalleFacturacion = new HashSet<DetalleFacturacion>();
        }
    
        public int IDProducto { get; set; }
        public decimal Precio { get; set; }
        public string NombreProducto { get; set; }
        public string EstadoProducto { get; set; }
        public string ExistenciaProducto { get; set; }
        public string Categoria { get; set; }
        public int IDProveedor { get; set; }
        public int Stock { get; set; }
        public string ImgProducto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleCarrito> DetalleCarrito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleFacturacion> DetalleFacturacion { get; set; }
        public virtual Proveedores Proveedores { get; set; }
    }
}
